name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build client
      run: |
        cd client
        cargo build --verbose

    - name: Test client
      run: |
        cd client
        cargo test --verbose

    - name: Build server
      run: |
        cd server
        cargo build --verbose

    - name: Test server
      run: |
        cd server
        cargo test --verbose
